In [91]:
import pandas as pd
import numpy as np
df = pd.read_csv('Students.csv')

In [19]:
df.head()

   Student_ID   Name  Python  Maths  Statistics  Attendance
0         101  Aarav      85   78.0        92.0        95.0
1         102   Diya      67   88.0        74.0        82.0
2         103  Rahul      45   56.0        61.0        68.0
3         104  Priya      92   95.0        89.0        98.0
4         105  Krish      76   72.0        80.0        85.0

In [20]:
df.tail(3)

    Student_ID   Name  Python  Maths  Statistics  Attendance
17         117   Riya      35   42.0        38.0        55.0
18         118  Manav      84   89.0        81.0        92.0
19         119  Tanvi      71   77.0        85.0        84.0

In [21]:
df.isna() #missing values

    Student_ID   Name  Python  Maths  Statistics  Attendance
0        False  False   False  False       False       False
1        False  False   False  False       False       False
2        False  False   False  False       False       False
3        False  False   False  False       False       False
4        False  False   False  False       False       False
5        False  False   False  False       False       False
6        False  False   False  False       False       False
7        False  False   False  False       False       False
8        False  False   False  False       False       False
9        False  False   False  False       False       False
10       False  False   False  False       False       False
11       False  False   False   True       False       False
12       False  False   False  False       False       False
13       False  False   False  False        True       False
14       False  False   False  False       False       False
15       False  False   False  False       False       False
16       False  False   False  False       False        True
17       False  False   False  False       False       False
18       False  False   False  False       False       False
19       False  False   False  False       False       False

In [22]:
df.describe()  #Generate a statistical summary.

       Student_ID     Python      Maths  Statistics  Attendance
count    20.00000  20.000000  19.000000   19.000000   19.000000
mean    110.25000  70.650000  73.842105   75.473684   82.052632
std       5.59017  17.980326  15.008380   15.363624   12.795284
min     101.00000  35.000000  42.000000   38.000000   55.000000
25%     105.75000  60.250000  66.500000   69.000000   74.000000
50%     110.50000  74.500000  77.000000   77.000000   85.000000
75%     115.00000  84.250000  84.500000   86.500000   91.500000
max     119.00000  95.000000  95.000000   96.000000   98.000000

In [23]:
print("Rows:",df.shape[0])
print('Cols:',df.shape[1])

Rows: 20
Cols: 6

In [24]:
df.dtypes

Student_ID      int64
Name              str
Python          int64
Maths         float64
Statistics    float64
Attendance    float64
dtype: object

In [36]:
duplicates = df[df.duplicated(keep=False)]  #fetching all the duplicated rows 
duplicates

    Student_ID Name  Python  Maths  Statistics  Attendance
14         115  Jay      79   83.0        75.0        88.0
15         115  Jay      79   83.0        75.0        88.0

In [27]:
df.isnull().sum() #missing values exist in each col

Student_ID    0
Name          0
Python        0
Maths         1
Statistics    1
Attendance    1
dtype: int64

In [41]:
# want to check only for specific student id's
df[df.duplicated(subset=['Student_ID'],keep=False)]

    Student_ID Name  Python  Maths  Statistics  Attendance
14         115  Jay      79   83.0        75.0        88.0
15         115  Jay      79   83.0        75.0        88.0

In [49]:
x= df[df.isnull().any(axis = 1)]  #rows containing at least one missing value

    Student_ID     Name  Python  Maths  Statistics  Attendance
11         112     Neha      61    NaN        70.0        76.0
13         114     Siya      48   55.0         NaN        65.0
16         116  Krishna      66   71.0        68.0         NaN

In [50]:
(df.isna().sum() / len(df)) * 100  #finding the percentage of missing values in each column

Student_ID    0.0
Name          0.0
Python        0.0
Maths         5.0
Statistics    5.0
Attendance    5.0
dtype: float64

In [67]:
# Handling the missing values
# For missing subject marks, consider replacing them with that subject's median
select_col = df.isnull().any(axis=1)
df[select_col]
df_clean = df.copy()

df_clean['Maths'] = df_clean['Maths'].fillna(df_clean['Maths'].median())
df_clean['Statistics'] = df_clean['Statistics'].fillna(df_clean['Statistics'].median())
df_clean['Attendance'] = df_clean['Attendance'].fillna(df_clean['Attendance'].median())
df_clean.isna().sum()  #check the missing values are handled or not

Student_ID    0
Name          0
Python        0
Maths         0
Statistics    0
Attendance    0
dtype: int64

In [81]:
df_final= df_clean.drop_duplicates()  #Remove duplicate records

In [84]:
df_final.isna().any(axis=1)  #check for the null values

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
16    False
17    False
18    False
19    False
dtype: bool

In [86]:
df_final.reset_index(drop=True)

    Student_ID     Name  Python  Maths  Statistics  Attendance
0          101    Aarav      85   78.0        92.0        95.0
1          102     Diya      67   88.0        74.0        82.0
2          103    Rahul      45   56.0        61.0        68.0
3          104    Priya      92   95.0        89.0        98.0
4          105    Krish      76   72.0        80.0        85.0
5          106    Anaya      58   64.0        55.0        72.0
6          107    Rohan      88   81.0        85.0        91.0
7          108    Meera      39   48.0        52.0        60.0
8          109    Arjun      73   69.0        77.0        80.0
9          110     Isha      95   91.0        96.0        97.0
10         111    Kabir      82   75.0        88.0        89.0
11         112     Neha      61   77.0        70.0        76.0
12         113      Dev      90   86.0        93.0        94.0
13         114     Siya      48   55.0        77.0        65.0
14         115      Jay      79   83.0        75.0        88.0
15         116  Krishna      66   71.0        68.0        85.0
16         117     Riya      35   42.0        38.0        55.0
17         118    Manav      84   89.0        81.0        92.0
18         119    Tanvi      71   77.0        85.0        84.0

In [88]:
df_final['Total'] = df[['Python','Statistics','Maths']].sum(axis=1)
df_final

    Student_ID     Name  Python  Maths  Statistics  Attendance  Total
0          101    Aarav      85   78.0        92.0        95.0  255.0
1          102     Diya      67   88.0        74.0        82.0  229.0
2          103    Rahul      45   56.0        61.0        68.0  162.0
3          104    Priya      92   95.0        89.0        98.0  276.0
4          105    Krish      76   72.0        80.0        85.0  228.0
5          106    Anaya      58   64.0        55.0        72.0  177.0
6          107    Rohan      88   81.0        85.0        91.0  254.0
7          108    Meera      39   48.0        52.0        60.0  139.0
8          109    Arjun      73   69.0        77.0        80.0  219.0
9          110     Isha      95   91.0        96.0        97.0  282.0
10         111    Kabir      82   75.0        88.0        89.0  245.0
11         112     Neha      61   77.0        70.0        76.0  131.0
12         113      Dev      90   86.0        93.0        94.0  269.0
13         114     Siya      48   55.0        77.0        65.0  103.0
14         115      Jay      79   83.0        75.0        88.0  237.0
16         116  Krishna      66   71.0        68.0        85.0  205.0
17         117     Riya      35   42.0        38.0        55.0  115.0
18         118    Manav      84   89.0        81.0        92.0  254.0
19         119    Tanvi      71   77.0        85.0        84.0  233.0

In [90]:
df_final['Average'] = df[['Python','Statistics','Maths']].mean(axis=1)

In [97]:

conditions = [
    df_final['Average'] >= 85,
    (df_final['Average'] >= 70) & (df_final['Average'] < 85),
    (df_final['Average'] >= 50) & (df_final['Average'] < 70),
    df_final['Average'] < 50
]

grades = ['A', 'B', 'C', 'D']

df_final['Grade'] = np.select(conditions, grades, default='F')
df_final[['Name', 'Average', 'Grade']]

       Name    Average Grade
0     Aarav  85.000000     A
1      Diya  76.333333     B
2     Rahul  54.000000     C
3     Priya  92.000000     A
4     Krish  76.000000     B
5     Anaya  59.000000     C
6     Rohan  84.666667     B
7     Meera  46.333333     D
8     Arjun  73.000000     B
9      Isha  94.000000     A
10    Kabir  81.666667     B
11     Neha  65.500000     C
12      Dev  89.666667     A
13     Siya  51.500000     C
14      Jay  79.000000     B
16  Krishna  68.333333     C
17     Riya  38.333333     D
18    Manav  84.666667     B
19    Tanvi  77.666667     B

In [108]:
condition2 = (
    (df_final['Python'] >= 40) &
    (df_final['Statistics'] >= 40) &
    (df_final['Maths'] >= 40)
)

df_final['Result'] = np.where(condition2, "Pass", "Fail")

df_final[['Name', 'Python', 'Maths', 'Statistics', 'Result']]

       Name  Python  Maths  Statistics Result
0     Aarav      85   78.0        92.0   Pass
1      Diya      67   88.0        74.0   Pass
2     Rahul      45   56.0        61.0   Pass
3     Priya      92   95.0        89.0   Pass
4     Krish      76   72.0        80.0   Pass
5     Anaya      58   64.0        55.0   Pass
6     Rohan      88   81.0        85.0   Pass
7     Meera      39   48.0        52.0   Fail
8     Arjun      73   69.0        77.0   Pass
9      Isha      95   91.0        96.0   Pass
10    Kabir      82   75.0        88.0   Pass
11     Neha      61   77.0        70.0   Pass
12      Dev      90   86.0        93.0   Pass
13     Siya      48   55.0        77.0   Pass
14      Jay      79   83.0        75.0   Pass
16  Krishna      66   71.0        68.0   Pass
17     Riya      35   42.0        38.0   Fail
18    Manav      84   89.0        81.0   Pass
19    Tanvi      71   77.0        85.0   Pass

In [109]:
df_final.sort_values(by='Average')

,Student_ID,Name,Python,Maths,Statistics,Attendance,Total,Average,Grade,Result
17,117,Riya,35,42.0,38.0,55.0,38.333333,38.333333,D,Fail
7,108,Meera,39,48.0,52.0,60.0,46.333333,46.333333,D,Fail
13,114,Siya,48,55.0,77.0,65.0,51.500000,51.500000,C,Pass
2,103,Rahul,45,56.0,61.0,68.0,54.000000,54.000000,C,Pass
5,106,Anaya,58,64.0,55.0,72.0,59.000000,59.000000,C,Pass
11,112,Neha,61,77.0,70.0,76.0,65.500000,65.500000,C,Pass
16,116,Krishna,66,71.0,68.0,85.0,68.333333,68.333333,C,Pass
8,109,Arjun,73,69.0,77.0,80.0,73.000000,73.000000,B,Pass
4,105,Krish,76,72.0,80.0,85.0,76.000000,76.000000,B,Pass
1,102,Diya,67,88.0,74.0,82.0,76.333333,76.333333,B,Pass
19,119,Tanvi,71,77.0,85.0,84.0,77.666667,77.666667,B,Pass
14,115,Jay,79,83.0,75.0,88.0,79.000000,79.000000,B,Pass
10,111,Kabir,82,75.0,88.0,89.0,81.666667,81.666667,B,Pass
18,118,Manav,84,89.0,81.0,92.0,84.666667,84.666667,B,Pass
6,107,Rohan,88,81.0,85.0,91.0,84.666667,84.666667,B,Pass
0,101,Aarav,85,78.0,92.0,95.0,85.000000,85.000000,A,Pass
12,113,Dev,90,86.0,93.0,94.0,89.666667,89.666667,A,Pass
3,104,Priya,92,95.0,89.0,98.0,92.000000,92.000000,A,Pass
9,110,Isha,95,91.0,96.0,97.0,94.000000,94.000000,A,Pass

In [111]:
df_final[['Name', 'Average', 'Grade','Result']].sort_values(by='Average',ascending=False).head()

     Name    Average Grade Result
9    Isha  94.000000     A   Pass
3   Priya  92.000000     A   Pass
12    Dev  89.666667     A   Pass
0   Aarav  85.000000     A   Pass
6   Rohan  84.666667     B   Pass

In [119]:
df_final[df_final['Result'] == 'Fail'][['Name','Python' ,'Maths','Statistics','Average', 'Grade','Result']]

     Name  Python  Maths  Statistics    Average Grade Result
7   Meera      39   48.0        52.0  46.333333     D   Fail
17   Riya      35   42.0        38.0  38.333333     D   Fail